title: Ken's Models

flickr_usernam: kens_models

collections_dir: collections

collections:

  aircraft:
    builds: true
    display_name: Aircraft
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721726619581/
    image: /img/collection-aircraft.jpg
    output: true
    position: 3
    url: /aircraft.html

  buildings:
    builds: true
    display_name: Buildings
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721664796542/
    image: /img/collection-buildings.jpg
    output: true
    position: 6
    url: /buildings.html

  carsandtrucks:
    builds: true
    display_name: Cars & trucks
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721687938947/
    image: /img/collection-carsandtrucks.jpg
    output: true
    position: 4
    url: /cars-and-trucks.html

  rail:
    builds: true
    display_name: Rail
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721732178630/
    image: /img/collection-rail.jpg
    output: true
    position: 5
    url: /rail.html

  ships:
    builds: true
    display_name: Ships
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721664798767/
    image: /img/collection-ships.jpg
    output: true
    position: 1
    url: /ships.html

  militaryvehicles:
    builds: true
    display_name: Military vehicles
    flickr_url: https://www.flickr.com/photos/kens_models/collections/72157721652476868/
    image: /img/collection-militaryvehicles.jpg
    output: true
    position: 2
    url: /military-vehicles.html

excerpt_separator: <!--more-->

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3
